version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /src
    volumes:
      - .:/src
    command:
      "/bin/sh -c 'node index.js'"
